### ISSUE TITLE
 ros-humble- Gazebo-ros-pkgs   failed to install

### ISSUE THREAD

**Issue by Alchemistqqqq** [tomasvr/turtlebot3_drlnav#11]
Hello, we are going to deploy the project on a real robot. Our robot development board is Ubuntu22.04, arm architecture. When installing gazebo, sudo apt install ros-humble- Gazebo-ros-pkgs failed to install, resulting in a failure to compile the gazebo feature pack. How to solve this problem if you want to deploy to physical robots.

**Comment by oscar2396** [comment]
Thanks for your solutions its really help me..!!!
Now i am trying to implement an environment with two robots with the trained network, do you know what para meters i need to duplicate with other name to run the goal and the trained network? I am new in this could you help?

**Comment by tomasvr** [comment]
> Hello, we are going to deploy the project on a real robot. Our robot development board is Ubuntu22.04, arm architecture. When installing gazebo, sudo apt install ros-humble- Gazebo-ros-pkgs failed to install, resulting in a failure to compile the gazebo feature pack. How to solve this problem if you want to deploy to physical robots.

Unfortunately, I have not adapted and tested this project with ros-humble so currently ros-foxy is required.

**Comment by tomasvr** [comment]
> Thanks for your solutions its really help me..!!! Now i am trying to implement an environment with two robots with the trained network, do you know what para meters i need to duplicate with other name to run the goal and the trained network? I am new in this could you help?

I think this would be rather challenging and require a considerable amount of effort to work properly. The easiest thing to do would be to have to machines each running their own agent instance on a shared ROS network with a single gazebo simulation. That would require renaming all of the ros topics ('scan', 'cmd_vel', 'odom', etc) to avoid naming conflicts.
